pipeline {
    agent any

    stages {
        stage('Clonar o repositório') {
            steps {
                git branch: 'main', url: 'https://github.com/RaphaelLimaSouza/exercicio-ebac-M15.git'
            }
        }

        stage('Instalar dependências e Executar testes') {
            steps {
                dir('exercicio-M12-e2e') {
                    bat 'npm install'
                    bat 'npx cypress run'
                }
            }
        }
    }
}